export const URL_LOGIN = '/signin'
export const URL_REGISTER = '/signup'
export const URL_UPLOAD_IMAGE = '/upload-image'
export const URL_CHANGE_PASSWORD = '/change-password'
export const URL_FORGOT_PASSWORD = '/forgot-password'
export const URL_RESET_PASSWORD = '/reset-password'
